#!/bin/bash

echo "Get connection info .."

cert=$(base64 -w0 ../.lit/tls.cert)
macaroon=$(base64 -w0 .lnd/data/chain/bitcoin/mainnet/admin.macaroon)
echo "{
	\"cert\":\"$cert\",
	\"macaroon\":\"$macaroon\",
	\"socket\":\"lit:10009\"
}"

