#!/bin/bash

###############################################################################
# Nimble Node - Start all containers
###############################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

echo "Starting Nimble Node containers .."
docker compose up -d
